services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: timescaledb_data
        target: /var/lib/postgresql/data
    networks:
      - crypto-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    volumes:
      - type: volume
        source: pgadmin_data
        target: /var/lib/pgadmin
    depends_on:
      - timescaledb
    networks:
      - crypto-network

volumes:
  timescaledb_data:
  pgadmin_data:

networks:
  crypto-network:
    driver: bridge
