services:
  bdd-postgresql:
    image: postgres:latest
    container_name: bdd-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: bdd_postgres_data
        target: /var/lib/postgresql/data
    networks:
      - bdd-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: bdd-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    volumes:
      - type: volume
        source: bdd_pgadmin_data
        target: /var/lib/pgadmin
    depends_on:
      - bdd-postgresql
    networks:
      - bdd-network

volumes:
  bdd_postgres_data:
    external: false
  bdd_pgadmin_data:
    external: false

networks:
  bdd-network:
    driver: bridge
