#version: "3.9"
services:
  prometheus:
    image: bitnami/prometheus:latest
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: bind
        source: ./alerts.yml
        target: /etc/prometheus/rules/alerts.yml
      - type: volume
        source: prometheus-data
        target: /prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - prometheus-grafana-network
    restart: always

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    volumes:
      - type: volume
        source: grafana-data
        target: /var/lib/grafana
      - type: bind
        source: ./grafana/provisioning/datasources
        target: /etc/grafana/provisioning/datasources
      - type: bind
        source: ./grafana/provisioning/dashboards
        target: /etc/grafana/provisioning/dashboards
      - type: bind
        source: ./grafana/provisioning/dashboards/default.yaml
        target: /etc/grafana/provisioning/dashboards/default.yaml
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${MDP}
    networks:
      - prometheus-grafana-network
    restart: always

  node-exporter:
    image: bitnami/node-exporter:latest
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - '^/(sys|proc|dev|host|etc)($|/)'
      - '--collector.systemd'
      - '--collector.processes'
    ports:
      - "9100:9100"
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
    networks:
      - prometheus-grafana-network
    restart: always

  alertmanager:
    image: bitnami/alertmanager:latest
    volumes:
      - type: bind
        source: ./alertmanager.yml
        target: /opt/bitnami/alertmanager/conf/config.yml
      - type: volume
        source: alertmanager-data
        target: /opt/bitnami/alertmanager/data
    ports:
      - "9093:9093"
    command:
      - '--config.file=/opt/bitnami/alertmanager/conf/config.yml'
      - '--storage.path=/opt/bitnami/alertmanager/data'
      - '--web.external-url=http://localhost:9093'
    networks:
      - prometheus-grafana-network
    restart: always

volumes:
  grafana-data:
  prometheus-data:
  alertmanager-data:

networks:
  prometheus-grafana-network:
    driver: bridge
