version: '3.8'
services:
  vm1: 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vm1
    tty: true
    stdin_open: true
    networks:
      - multi_vm_net
    restart: always
    hostname: vm1
    ports:
      - "2232:22"
      - "8080:80"
  vm2: 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vm2
    tty: true
    stdin_open: true
    networks:
      - multi_vm_net
    restart: always
    hostname: vm2
    ports:
      - "2233:22"
      - "9090:9090"
      - "3000:3000"
  vm3:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vm3
    tty: true
    stdin_open: true
    networks:
      - multi_vm_net
    restart: always
    hostname: vm3
    ports:
      - "2234:22"
      - "3333:3306"
networks:
  multi_vm_net:
   