FROM python:3.10-alpine
RUN apk add --no-cache \
    build-base \
    libffi-dev \
    openssl-dev \
    sshpass \
    openssh-client && \
    pip install --upgrade pip && \
    pip install cffi ansible
RUN ansible --version
WORKDIR /ansible
CMD ["ansible-playbook", "--version"]

