version: "3.8"

services:
  gitlab:
    image: gitlab/gitlab-ce:17.6.3-ce.0 # ← version figée
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://freedude.freeboxos.fr/gitlab'
        gitlab_rails['gitlab_relative_url'] = "/gitlab"
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['gitlab_ssh_port']  = 2224
        nginx['listen_port']  = 80
        nginx['listen_https'] = false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`freedude.freeboxos.fr`) && PathPrefix(`/gitlab`)"
      - "traefik.http.routers.gitlab.entrypoints=websecure"
      - "traefik.http.routers.gitlab.tls.certresolver=myresolver"
      - "traefik.http.services.gitlab.loadbalancer.passhostheader=true"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
    ports:
      - "2224:22"
    expose:
      - "80"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    networks:
      - gerardinho-network

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine-v17.6.0 # ← version figée
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner-config:/etc/gitlab-runner
      - gitlab-runner-certs:/certs/client # recommandé par la doc
      - gitlab-runner-cache:/cache
    networks:
      - gerardinho-network

volumes:
  gitlab-config: { external: true }
  gitlab-logs: { external: true }
  gitlab-data: { external: true }
  gitlab-runner-config: { external: true }
  gitlab-runner-certs: { external: true }
  gitlab-runner-cache: { external: true }

networks:
  gerardinho-network: { external: true }
